routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.master');
});

// Route::get('/login', function () {
//     return view('layouts.master');
// });

// CRUD Login & Sign Up
Route::get('/signup', 'SignUpController@signup' );
Route::get('/login', 'SignUpController@login' );

// CRUD MATKUL 
Route::get('/matkul/create', 'MatkulController@create' );
Route::post('/matkul', 'MatkulController@store' );
Route::get('/matkul', 'MatkulController@index' );
Route::get('/matkul/{matkul_id}', 'MatkulController@show' );
Route::get('/matkul/{matkul_id}/edit', 'MatkulController@edit' );
Route::put('/matkul/{matkul_id}', 'MatkulController@update' );
Route::delete('/matkul/{matkul_id}', 'MatkulController@destroy' );

// CRUD PERTANYAAN
Route::get('/pertanyaan/create', 'PertanyaanController@create');
Route::post('/pertanyaan', 'PertanyaanController@store');
Route::get('/pertanyaan', 'PertanyaanController@index');
Route::get('/pertanyaan/{pertanyaan_id}', 'PertanyaanController@show');
Route::get('/pertanyaan/{pertanyaan_id}/edit', 'PertanyaanController@edit');
Route::put('/pertanyaan/{pertanyaan_id}', 'PertanyaanController@update');
Route::delete('/pertanyaan/{pertanyaan_id}', 'PertanyaanController@destroy');

// CRUD Profil
Route::get('/profil/create', 'ProfileController@create' );
Route::post('/profil', 'ProfileController@store' );
Route::get('/profil', 'ProfileController@index' );
Route::get('/profil/{matkul_id}', 'ProfileController@show' );
Route::get('/profil/{matkul_id}/edit', 'ProfileController@edit' );
Route::put('/profil/{matkul_id}', 'ProfileController@update' );
Route::delete('/profil/{matkul_id}', 'ProfileController@destroy' );

Route::resource('pertanyaan', 'PertanyaanController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/pertanyaan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class pertanyaan extends Model
{
    protected $table = "pertanyaan";
    protected $fillable = ['pertanyaan','matkul_id'];
}

app/Http/Controllers/PertanyaanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\pertanyaan;
use App\matkul;


class PertanyaanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pertanyaan = pertanyaan::all();
        return view('layouts.pertanyaan.index', compact('pertanyaan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $matkul = matkul::all();
        return view ('layouts.pertanyaan.create', compact('matkul'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            // 'nama' => 'required|unique:pertanyaan,nama|max:255',
            'pertanyaan' => 'required',
            'FotoPertanyaan' => 'required|mimes:png,jpg,jpeg',
            'matkul_id'=>'required',
        ]);

        $fileName = time().'.'.$request->FotoPertanyaan->extension();

        $matkul = new pertanyaan;

        $matkul->pertanyaan = $request->pertanyaan;
        $matkul->FotoPertanyaan = $fileName;
        $matkul->matkul_id = $request->matkul_id;

        $request->save();

        $request->FotoPertanyaan->move(public_path('images'), $fileName);

        return redirect('/pertanyaan/create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $pertanyaan = pertanyaan::findorfail($id);
        return view('layouts.pertanyaan.show', compact('pertanyaan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $matkul = matkul::all();
        $pertanyaan = pertanyaan::findorfail($id);
        return view('layouts.pertanyaan.edit', compact('pertanyaan','matkul'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layouts/pertanyaan/create.blade.php
@extends('layouts.master')

@section('title')
    Tuliskan Pertanyaan mu!
@endsection

@section('content')
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">

        <form class="forms-sample" action="/pertanyaan/create" method="POST" enchtype="multipart/form-data">
            @csrf
            @method('put')
            {{-- <div class="form-group">
              <label for="title" >Nama</label>
              <input type="text" class="form-control" id="title" name="nama" placeholder="Name">

            </div> --}}
            <div class="form-group">
              <label for="title" >Upload pertanyaanmu disini!</label>
              <input type="file" class="form-control" name="FotoPertanyaan" >
            </div>
            <div class="form-group">
              <label>Masukkan Penjelasan dari Pertanyaanmu</label>
              <textarea class="form-control" name="pertanyaan" rows="5"></textarea>
            </div>
            <div class="form-group">
                <label>Mata Kuliah</label>
                <select name="matkul_id" class="form-control" id="">
                  <option value="">-- Pilih Mata Kuliah --</option>
                  @foreach ($matkul as $item)
                      <option value="{{$item->id}}"> {{$item->nama}}</option>
                  @endforeach
                </select>
              </div>
             
            <button type="submit" class="btn btn-primary mr-2">Submit</button>
          </form>
      </div>
    </div>
  </div>
@endsection

resources/views/layouts/pertanyaan/edit.blade.php
@extends('layouts.master')

@section('title')
    Edit Pertanyaan mu!
@endsection

@section('content')
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">

        <form class="forms-sample" action="/pertanyaan/{{$pertanyaan->id}}" method="POST" enchtype="multipart/form-data">
            @csrf
            {{-- @method('put') --}}
            {{-- <div class="form-group">
              <label for="title" >Nama</label>
              <input type="text" class="form-control" id="title" name="nama" placeholder="Name">
            </div> --}}
            <div class="form-group">
              <label for="title" >Upload pertanyaanmu disini!</label>
              <input type="file" class="form-control" name="FotoPertanyaan" >
            </div>
            <div class="form-group">
              <label>Masukkan Penjelasan dari Pertanyaanmu</label>
              <textarea class="form-control" value="{{$pertanyaan->pertanyaan}} name="pertanyaan" rows="5"></textarea>
            </div>
            <div class="form-group">
                <label>Mata Kuliah</label>
                <select name="matkul_id" class="form-control" id="">
                    <option value="">-- Pilih Mata Kuliah --</option>
                    @foreach ($matkul as $item)
                        @if ($item->id === $pertanyaan->matkul_id)
                            <option value="{{$item->id}}" selected> {{$item->nama}}</option>
                         @else
                            <option value="{{$item->id}}"> {{$item->nama}}</option>
                        @endif
                  @endforeach
                </select>
              </div>
              {{-- <a href="/pertanyaan/" class="btn btn-primary mr-2">submit</a> --}}
            <button type="submit" class="btn btn-primary mr-2">Submit</button>
          </form>
      </div>
    </div>
  </div>
@endsection

resources/views/layouts/pertanyaan/index.blade.php
            @extends('layouts.master')

@section('title')
    Pertanyaan
@endsection

@section('content')
  <div class="col-md-4 stretch-card grid-margin">
    <div class="card">
      <div class="card-body">
        <ul class="icon-data-list">
          <li>
            <a href="/pertanyaan/create" class="btn btn-info btn-sm">Tambah Pertanyaan</a>
            <div class="d-flex">
              @forelse ($pertanyaan as $item)
                <img src="{{asset('images/'.$item->FotoPertanyaan)}}" alt="user">
                  <div class="card">
                    <p class="text-info mb-1">{{$item->matkul_id}}</p>                    
                    <p class="mb-0">{{$item->pertanyaan}}</p>
                           <form action="{{route('pertanyaan.destroy',$item->id)}}" method="POST">
                      @csrf
                      @method('delete')
                      <a href="{{route('pertanyaan.show',$item->id)}}" class="btn btn-info btn-sm">Jawab</a>
                      <a href="{{route('pertanyaan.edit',$item->id)}}" class="btn btn-info btn-sm">Edit</a>
                      <input type="submit" class="btn btn-danger btn-sm" value="Delete"></input>
                    </form>
                  </div>

                    <button type="button" class="btn btn-outline-light btn-fw">Jawab</button>
                
                    </div>

                @empty
                  <label>Belum ada pertanyaan</label>
              @endforelse
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
@endsection

resources/views/layouts/pertanyaan/show.blade.php
@extends('layouts.master')

@section('title')
    Tuliskan Pertanyaan mu!
@endsection

@section('content')

@endsection